name: LeetCodeWidget
options:
  bundleIdPrefix: com.souravh
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  LeetCodeWidget:
    type: application
    platform: macOS
    sources:
      - path: LeetCodeWidget
        type: group
      - path: Shared
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.souravh.leetcodewidget
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        CODE_SIGN_ENTITLEMENTS: LeetCodeWidget/LeetCodeWidget.entitlements
        ENABLE_HARDENED_RUNTIME: true
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
    entitlements:
      path: LeetCodeWidget/LeetCodeWidget.entitlements
    dependencies:
      - target: LeetCodeWidgetExtension

  LeetCodeWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: LeetCodeWidgetExtension
        type: group
      - path: Shared
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.souravh.leetcodewidget.extension
        CODE_SIGN_ENTITLEMENTS: LeetCodeWidgetExtension/LeetCodeWidgetExtension.entitlements
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        SKIP_INSTALL: true
        INFOPLIST_KEY_CFBundleDisplayName: LeetCodeWidgetExtension
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
    entitlements:
      path: LeetCodeWidgetExtension/LeetCodeWidgetExtension.entitlements
